version: 2
updates:
  # Enable version updates for Docker
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/images/docker/cpp-python-devel-centos8/Dockerfile/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
